version: '3'
services:
    api_dev:
        build:
            context: .
            dockerfile: Dockerfile
        network_mode: host
        ports:
            - 3000:3000
        env_file:
            - .env
        volumes:
            - ./src:/app/src
            - ./global.d.ts:/app/global.d.ts
        command: npm run dev
