version: "3"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SanMiguel123
      MYSQL_DATABASE: SanMiguel
    volumes:
      - ./db/sanmiguel.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

